language: node_js
cache:
  directories:
  - node_modules

notifications:
  email: false

scripts:
  - npm run test
  - npm run apidoc

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ytkAZx7VE4Dl+lOIU2bmFju3rtMPRUm1rvu0BqQqQNVdsqRCz1SEmUfxisEib46yG/bazu1hlayTz1y3qY/T/Bmg5Dss7jBJ1xLOM5WYFNFRXCqG6/fv2IbD/swHkjPxvLSjhocSuAkJ9NiHfM+yYBTYVil1vjFtId9vkfyGgqY6hyV4QsjaM7YsX7/8POqvkCmAet+tExFvldtFCX2CyCbwNSHmiJg5jtQAwsDa2q2juk78KWLPmNMYQFJYeCGt0xu+F/+MToxUEIUyIVndnLEpYVbH0PbzkDlv+Aaew1biMB6hM1d0DX0hJJQyDQUwyc3LsqtRNLsZne2wGFGsWuJn3DxstMyut6ita9IYDxUvtBIXGIIb3ZFnAHsi26IsUHh4J2r3UIuYcjn/Dj63LiRmg5N6wwuHp3J2PYzZJmZ0efAhwHZUlB/YhsH2P7uq0cvyvme3JSuvmnkv9qfPhp0VBnKDurTvjYJPtWtaLDlyhAbv5XaHBpwd/AHvQ7JdoLBDdEKfmq2W2oIHWQtbQiXP1Mf3P8BtQIh4PaA60/qfdcgIJW6H2VdWfIzB4dwsLApLXl5no650qm3PUBFvbEOxl+rrpfvJGweZ9DgcvwiCDKFaTY2EOtx7McOzZle6JhyD7LieoIrOcvNPTnbROCy5fC3jck4+MFILKadFTVk=
  app: signsfive-api-staging
