version: '3'

services:
  database:
    container_name: signsfive_database
    image: mariadb
    volumes:
      - ${DATABASE_DOCKER}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      signsfive_net:
        ipv4_address: ${NETWORK_DATABASE}

  api:
    depends_on:
      - database
    volumes:
      - ./.npm:/home/node/.npm
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${NETWORK_DATABASE}
    networks:
        signsfive_net:
          ipv4_address: ${NETWORK_API}

  phpmyadmin:
    container_name: signsfive_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${NETWORK_DATABASE}:${MYSQL_PORT}
    networks:
      signsfive_net:
        ipv4_address: ${NETWORK_PHPMYADMIN}

volumes:
  db_data:

networks:
  signsfive_net:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
